// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.598
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Admin(current_page string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<script src=\"https://unpkg.com/htmx.org@1.9.10\" integrity=\"sha384-D1Kt99CQMDuVetoL1lrYwg5t+9QdHe7NLX/SoJYkXDFfX37iInKRy5xLSi8nO7UC\" crossorigin=\"anonymous\"></script><style type=\"text/css\">\n        button {\n            width : 200px ; \n            height : 60px ;\n            background-color : white ;\n            color : black ;\n            font-weight: bolder ;\n            border : none ;\n            border-radius : 5px ;\n            margin : 6px ;\n            font-size : 14px ;\n        }\n        button:hover {\n            background-color : rgb(180, 180, 180) ;\n        }\n        .admin-container {\n            display : flex ;\n            align-items : center ;\n            justify-content : center ;\n            flex-direction : column ;\n        }\n    </style><div class=\"admin-container\"><button id=\"user-btn\" hx-get=\"/ctrl\" target=\"#user-btn\" hx-swap=\"outerHTML\">USERS</button> <button>TICKETS</button> <button>PERMISSIONS</button> <button>ROLES</button></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}

// switch current_page {
//             case "user" :
//                 @Ctrl()
//                 <button>
//                     TICKETS
//                 </button>
//                 <button>
//                     ROLES
//                 </button>
//                 <button>
//                     PERMISSIONS
//                 </button>
//                 <button>
//                     CHATS
//                 </button>
//             case "ticket" :
//                 <button>
//                     USERS
//                 </button>
//                 <button>
//                     TICKETS
//                 </button>
//                 <button>
//                     ROLES
//                 </button>
//                 <button>
//                     PERMISSIONS
//                 </button>
//                 <button>
//                     CHATS
//                 </button>
//             case "permission" :
//                 <button>
//                     USERS
//                 </button>
//                 <button>
//                     TICKETS
//                 </button>
//                 <button>
//                     ROLES
//                 </button>
//                     @Ctrl()
//                 <button>
//                     CHATS
//                 </button>
//             case "role" :
//                 <button>
//                     USERS
//                 </button>
//                 <button>
//                     TICKETS
//                 </button>
//                     @Ctrl()
//                 <button>
//                     PERMISSIONS
//                 </button>
//                 <button>
//                     CHATS
//                 </button>
//         }
