// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.598
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Feed() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<style type=\"text/css\">\n    .ticket {\n            width : 70vw ;\n            height : 10vh ;\n            background-color : white ;\n            border : none ;\n            border-radius : 10px ;\n            display : flex ;\n            flex-direction : row ;\n            font-weight : bolder ;\n            align-items: center;\n            margin-top : 10px ;\n        }\n        .ticket > p {\n            margin-left : 20px ;\n            font-size : 20px ;\n        }\n        .ticket:hover {\n            background-color : rgb(219, 219, 219) ;\n        }\n        .id-container {\n            height : 10vh ; \n            width : 10vw ;\n            background-color : rgb(46, 46, 46) ;\n            position : relative ;\n            left : 0 ;\n            border-top-left-radius: 10px ;\n            border-bottom-left-radius: 10px ;\n            display : flex ; \n            align-items : center ;\n            justify-content : center ;\n            color : white ;\n            font-weight : bold ;\n            border : none ;\n        }\n        #feed {\n            width : 80vw ; \n            height : 100vh ;\n            display : flex ;\n            align-items : center ;\n            position : relative ;\n            overflow-y : scroll ;\n            flex-direction: column ;\n            gap : 10px ;\n            background-color : black ;\n        }\n    </style><div id=\"feed\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
