// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.598
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "InternshipProject/backend/types"

func Sidebar(user types.User) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<style type=\"text/css\">\n        .sidebar {\n            position : fixed ;\n            right: 0px ;\n            z-index : 1 ;\n            overflow-x : hidden ;\n            background-color: black; \n            width : 20vw ; \n            height : 100vh; \n            display : flex ;\n            justify-content : center ; \n            align-items : center ; \n            flex-direction: column ;\n            border-left : 2px solid white ;\n        }\n        button {\n            width : 200px ; \n            height : 60px ;\n            /* background-color: #3C3633 ;  */\n            background-color : white ;\n            /* color : #EEEDEB ;  */\n            color : black ;\n            font-weight: bolder ;\n            border : none ;\n            border-radius : 10px ;\n            margin : 6px ;\n            font-size : 14px ;\n        }\n        button:hover {\n            /* background-color: #747264 ; */\n            background-color : rgb(180, 180, 180) ;\n        }\n        .profile {\n            /* background-color : #3C3633 ; */\n            background-color: white ;\n            /* color : #EEEDEB ; */\n            color : black ;\n            padding : 20px ;\n            border : none ;\n            border-radius : 10px ;\n            width : 160px ;\n            /* position : absolute ;\n            bottom : 40px ; */\n            margin-top : 60px ;\n        }\n    </style><div class=\"sidebar\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
