// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.598
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func TicketForm() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<style>\n        textarea {\n            width : 70vw ;\n            height : 30vh ;\n            border : none ;\n            border-radius : 5px ;\n            margin : 10px ;\n            color : black ;\n        }\n        input {\n            width : 70vw ;\n            height : 60px ;\n            border : none ;\n            border-radius : 5px ;\n            color : black ;\n        }\n        form {\n            padding : 0 ;\n            margin : 0 ;\n            display : flex ;\n            align-items : center ;\n            flex-direction : column ;\n        }\n        #ticket {\n            width : 100% ;\n            height : 100% ;\n            display : flex ;\n            align-items : center ;\n            justify-content : center ;\n            flex-direction : column ;\n            position : absolute ;\n            top : 0 ;\n            left : 0 ;\n        }\n    </style><div id=\"ticket\"><form><input type=\"text\" name=\"title\" placeholder=\"TITLE : \"><div><textarea type=\"text\" name=\"content\" placeholder=\"CONTENT : \"></textarea></div><button hx-post=\"/user/ticketsub\" trigger=\"click\">SUBMIT</button></form></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}

//target="#ticket" hx-swap="innerHTML"
