// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.598
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Topbar() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<style type=\"text/css\">\n        .topbar {\n            background-color : rgb(180, 180, 180) ;\n            width : 70vw ;\n            height : 60px ;\n            border : none ;\n            border-radius : 5px ;\n            display : flex ;\n            flex-direction : row ;\n            justify-content: center ;\n            align-items : center ;\n            margin : 10px ;\n            position : sticky ;\n            top : 0 ;\n            z-index: 1000 ;\n            margin-top : 25px ;\n        }\n        .topbar  > div {\n            flex : 1 ;\n            margin : 0 ;\n            display : flex ;\n            align-items : center ;\n            justify-content : center ;\n            border-right : 1px solid black ;\n            font-weight : bolder ;\n        }\n    </style><div class=\"topbar\"><div>ID</div><div>USERNAME</div><div>EMAIL</div><div>PASSWORD</div><div>ROLE</div><div style=\"border : none ;\">BUREAU</div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
