// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.598
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Userform() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<style type=\"text/css\">\n    #user-form {\n        width : 100% ;\n        height : 100% ;\n        display : flex ;\n        align-items : center ;\n        justify-content : center ;\n        flex-direction : column ;\n        position : absolute ;\n        top : 0 ;\n        left : 0 ;\n    }\n    input {\n        width : 30vw ;\n        height : 60px ;\n        border : none ;\n        border-radius : 5px ;\n        color : black ;\n        margin : 6px ;\n        padding-left : 10px ;\n        size : 50%;\n    }\n    form {\n        padding : 0 ;\n        margin : 0 ;\n        display : flex ;\n        align-items : center ;\n        flex-direction : column ;\n    }\n    </style><div id=\"user-form\"><form hx-post=\"/submission\" trigger=\"submit\" hx-target-200=\"#user-form\"><input name=\"username\" placeholder=\"USERNAME\"> <input name=\"email\" placeholder=\"EMAIL\"> <input name=\"password\" placeholder=\"PASSWORD\"> <input name=\"confirm-password\" placeholder=\"CONFIRM PASSWORD\"> <input name=\"role\" placeholder=\"ROLE\"><button type=\"submit\">SUBMIT</button></form></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}

//type="text" name="username"
// type="email" name="email"
// type="password" name="password"
// type="password" name="confirm-password"
// type="text" name="role"
